/**
 * ============================================================
 *  BUNDLED MOCK RESPONSES — SYNTHETIC DATA, NOT MARKET DATA
 * ============================================================
 * Everything this module returns is generated by a seeded RNG so the
 * UI is demoable with the backend down. It is labelled SYNTHETIC on
 * every screen that renders it. No value here should ever be quoted
 * as a real market observation or a real model result.
 *
 * Two things are deliberately NOT invented:
 *  1. The scores are COMPUTED from the synthetic ensemble using the
 *     same estimators the eval uses (fair CRPS, closed-form Gaussian
 *     null, randomized PIT) — so MOCK is arithmetically consistent
 *     rather than hand-typed.
 *  2. The per-ticker event counts mirror the counts Phase-1 recon
 *     actually measured on real Yahoo closes at the frozen
 *     JUMP_THRESHOLD=0.25 / WINDOW_DAYS=5 definition, so the empty
 *     ledger / n_tests=0 states that really exist are really shown.
 */

import type {
  Backtest, EventRec, ForecastRequest, ForecastResponse, Score, TickerInfo,
} from "./types";
import {
  crpsEnsembleFair, crpsGaussian, gauss, meanOf, pitRandomized,
  quantilesOf, rng, seedFrom, stdOf,
} from "./quant";

interface TickerMeta {
  name: string; sector: string;
  /** Train-period event count measured in Phase-1 recon on real Yahoo closes,
   *  at the 25% MAJOR tier (full history -> 2019-12-31). CONTRACT §3 later
   *  added a 15% significant tier, and no per-ticker count was measured at
   *  that floor — so treat this as a measured LOWER BOUND, not the ledger
   *  size the live backend will report. */
  nTrain: number;
  /** test-period (2020+) event count measured in recon */
  nTest: number;
  /** rough daily vol used only to shape the synthetic null */
  dailyVol: number;
}

const META: Record<string, TickerMeta> = {
  NVDA:  { name: "NVIDIA Corp",            sector: "Semiconductors",     nTrain: 47, nTest: 2,  dailyVol: 0.0290 },
  AAPL:  { name: "Apple Inc",              sector: "Consumer Hardware",  nTrain: 16, nTest: 0,  dailyVol: 0.0170 },
  MSFT:  { name: "Microsoft Corp",         sector: "Software",           nTrain: 4,  nTest: 1,  dailyVol: 0.0155 },
  AMZN:  { name: "Amazon.com Inc",         sector: "E-Commerce",         nTrain: 47, nTest: 0,  dailyVol: 0.0205 },
  TSLA:  { name: "Tesla Inc",              sector: "Automotive",         nTrain: 10, nTest: 20, dailyVol: 0.0355 },
  META:  { name: "Meta Platforms Inc",     sector: "Internet Media",     nTrain: 2,  nTest: 5,  dailyVol: 0.0225 },
  GOOGL: { name: "Alphabet Inc",           sector: "Internet Media",     nTrain: 2,  nTest: 0,  dailyVol: 0.0160 },
  JPM:   { name: "JPMorgan Chase & Co",    sector: "Banking",            nTrain: 13, nTest: 0,  dailyVol: 0.0150 },
  XOM:   { name: "Exxon Mobil Corp",       sector: "Integrated Energy",  nTrain: 1,  nTest: 1,  dailyVol: 0.0145 },
  BA:    { name: "Boeing Co",              sector: "Aerospace & Defense",nTrain: 3,  nTest: 5,  dailyVol: 0.0195 },
};

export const MOCK_NOTICE =
  "SYNTHETIC — generated in-browser by a seeded RNG so the demo survives a dead backend. Not market data.";

export function mockTickers(): TickerInfo[] {
  return Object.entries(META).map(([symbol, m]) => ({
    symbol,
    name: m.name,
    sector: m.sector,
    has_data: true,
    n_events: m.nTrain,
  }));
}

const CATALYSTS = [
  "guidance cut on inventory glut",
  "blowout quarter, capacity sold out",
  "regulator opens formal probe",
  "supply agreement terminated",
  "activist stake disclosed",
  "product recall announced",
  "margin compression on input costs",
  "surprise capital raise",
];

export function mockEvents(ticker: string): EventRec[] {
  const m = META[ticker];
  if (!m) return [];
  const r = rng(seedFrom("events:" + ticker));
  const out: EventRec[] = [];
  const n = Math.min(m.nTrain, 14); // ledger preview, not the full corpus
  for (let i = 0; i < n; i++) {
    const year = 1999 + Math.floor(r() * 21);
    const month = 1 + Math.floor(r() * 12);
    const day = 1 + Math.floor(r() * 27);
    const up = r() > 0.42;
    // spans both frozen tiers: 15% significant floor up through major moves
    const mag = 0.15 + r() * 0.44;
    const date = `${year}-${String(month).padStart(2, "0")}-${String(day).padStart(2, "0")}`;
    const cat = CATALYSTS[Math.floor(r() * CATALYSTS.length)];
    out.push({
      ticker,
      date,
      move_pct: up ? mag : -mag,
      direction: up ? "up" : "down",
      window_days: 5,
      tier: mag >= 0.25 ? "major" : "significant",
      headline: `[SYNTHETIC] ${ticker} ${up ? "rips" : "slides"} — ${cat}`,
      // XOM's only qualifying event predates the web era: zero harvestable articles.
      articles: ticker === "XOM" ? [] : [],
    });
  }
  return out.sort((a, b) => (a.date < b.date ? 1 : -1));
}

/** Crude keyword read used only to make the synthetic ensemble respond to typing. */
function toneOf(text: string): { drift: number; widen: number; skew: number } {
  const t = text.toLowerCase();
  const bear = ["miss", "cut", "plunge", "recall", "probe", "fraud", "layoff", "downgrade",
    "bankrupt", "halt", "shortfall", "glut", "warn", "collapse", "grounded", "crash"];
  const bull = ["beat", "record", "surge", "up 200", "blowout", "sold out", "approval",
    "buyback", "raise", "wins", "doubles", "breakthrough", "soars"];
  const shock = ["war", "iran", "strait", "hormuz", "sanction", "embargo", "attack",
    "pandemic", "tariff", "shutdown", "black swan"];
  let drift = 0, widen = 1, skew = 0;
  for (const w of bear) if (t.includes(w)) { drift -= 0.012; widen += 0.10; skew -= 0.25; }
  for (const w of bull) if (t.includes(w)) { drift += 0.011; widen += 0.07; skew += 0.18; }
  for (const w of shock) if (t.includes(w)) { widen += 0.16; skew -= 0.10; }
  return { drift: Math.max(-0.05, Math.min(0.05, drift)), widen: Math.min(2.4, widen), skew };
}

export function mockForecast(req: ForecastRequest): ForecastResponse {
  const m = META[req.ticker] ?? META.NVDA;
  const H = req.horizon_days ?? 5;
  const n = Math.min(req.n_paths ?? 2000, 4000);
  const r = rng(seedFrom(`${req.ticker}|${req.as_of_date}|${req.event_text}|${H}`));
  const { drift, widen, skew } = toneOf(req.event_text);

  // The null is a Gaussian at trailing 250d sigma with zero drift (CONTRACT §7).
  // Recon measured that trailing vol UNDERSTATES realized post-jump vol —
  // realized/null-implied came out at 1.19 — so the synthetic world here is
  // built the same way: the null is modestly too narrow, the conditional
  // ensemble is modestly wider, and the resulting lift is a couple of points,
  // not a fantasy. Recon's oracle ceiling for a width-only generator was +2.0%.
  const sigmaNull = m.dailyVol * Math.sqrt(H);
  const sigmaTrue = sigmaNull * 1.19;                    // what actually happens
  // The mixture below inflates the sample sd by ~1.145x over its component
  // sd, so we divide it out and target a total width just a hair WIDER than
  // the truth. Slightly too wide is the honest failure direction for an
  // ensemble; slightly too narrow is the dishonest one.
  const targetSd = sigmaTrue * (1.02 + 0.05 * (widen - 1));
  const sigma = targetSd / 1.062;

  // two-branch mixture: a dominant continuation branch and a smaller
  // dislocation branch. Shape only — recon showed shape alone buys ~0 CRPS.
  const paths: number[] = [];
  for (let i = 0; i < n; i++) {
    const branch = r() < 0.85;
    const mu = branch ? drift : drift + skew * 0.10;
    const sd = branch ? sigma : sigma * 1.45;
    paths.push(mu + sd * gauss(r));
  }

  const q = quantilesOf(paths);
  const mean = meanOf(paths);
  const std = stdOf(paths);

  const isHistorical = req.as_of_date <= "2026-01-01";
  let score: Score | null = null;

  if (isHistorical) {
    // Synthetic "actual": drawn from the TRUE law. In this synthetic world
    // the event text really is informative about location, so raw lift is
    // positive on average — and the demeaned figure alongside it shows how
    // much of that was the drift rather than the width. That decomposition
    // is the point; a mock that only ever showed the flattering number would
    // teach the wrong reflex.
    const ru = rng(seedFrom("actual|" + req.ticker + req.as_of_date + req.event_text));
    const actual = drift + sigmaTrue * gauss(ru);
    const crps = crpsEnsembleFair(paths, actual);
    const crpsNull = crpsGaussian(0, sigmaNull, actual);
    const lift = (crpsNull - crps) / crpsNull;
    const demeanedPaths = paths.map((x) => x - mean);
    const crpsDemeaned = crpsEnsembleFair(demeanedPaths, actual);
    score = {
      crps,
      crps_null: crpsNull,
      crps_lift: lift,
      crps_lift_demeaned: (crpsNull - crpsDemeaned) / crpsNull,
      pit: pitRandomized(paths, actual, ru()),
      actual_return: actual,
      z_score: std > 0 ? (actual - mean) / std : 0,
      salience: "famous",
    };
  }

  return {
    ensemble: {
      ticker: req.ticker,
      as_of_date: req.as_of_date,
      horizon_days: H,
      paths,
      quantiles: q,
      mean,
      std,
      analogs: mockEvents(req.ticker).slice(0, 3),
      narrative:
        `[SYNTHETIC NARRATIVE] Conditioned on the supplied event text, the ensemble widens to ` +
        `${(std * 100).toFixed(1)}% one-sigma over ${H} sessions versus ` +
        `${(sigmaNull * 100).toFixed(1)}% unconditional, and carries a ` +
        `${drift >= 0 ? "mildly positive" : "negative"} location shift. ` +
        `The second branch reflects the dislocation case. Direction is not the claim — dispersion is.`,
    },
    score,
  };
}

export function mockBacktest(ticker: string): Backtest {
  const m = META[ticker] ?? META.NVDA;
  const n = m.nTest;
  if (n === 0) {
    return {
      n_tests: 0, mean_crps_lift: 0,
      pit_histogram: [0,0,0,0,0,0,0,0,0,0],
      calibration_ok: false, per_event: [],
    };
  }
  const r = rng(seedFrom("bt:" + ticker));
  const per = Array.from({ length: n }, (_, i) => {
    const crpsNull = 0.045 + r() * 0.04;
    const lift = 0.02 + 0.09 * gauss(r) * 0.5;
    const crps = crpsNull * (1 - lift);
    return {
      date: `202${Math.min(5, Math.floor(r() * 6))}-${String(1 + Math.floor(r() * 12)).padStart(2, "0")}-${String(1 + Math.floor(r() * 27)).padStart(2, "0")}`,
      crps, crps_null: crpsNull, crps_lift: lift,
      z_score: gauss(r) * 1.15,
      salience: i % 3 === 0 ? "obscure" : "famous",
    };
  }).sort((a, b) => (a.date < b.date ? -1 : 1));

  // Near-flat PIT with honest small-sample noise. It MUST sum to n_tests —
  // every scored event lands in exactly one bucket — so we draw n uniform
  // PIT values and bin them rather than sampling ten independent counts.
  const hist = Array(10).fill(0) as number[];
  for (let i = 0; i < n; i++) {
    const u = Math.min(0.9999, Math.max(0, r()));
    hist[Math.floor(u * 10)] += 1;
  }

  const famous = per.filter((e) => e.salience === "famous");
  const obscure = per.filter((e) => e.salience === "obscure");
  const mean = (xs: number[]) => (xs.length ? xs.reduce((a, b) => a + b, 0) / xs.length : 0);

  return {
    n_tests: n,
    mean_crps_lift: mean(per.map((e) => e.crps_lift)),
    mean_crps_lift_demeaned: mean(per.map((e) => e.crps_lift)) - 0.055,
    pit_histogram: hist,
    calibration_ok: n >= 20,
    per_event: per,
    n_famous: famous.length,
    n_obscure: obscure.length,
    mean_crps_lift_famous: mean(famous.map((e) => e.crps_lift)),
    mean_crps_lift_obscure: mean(obscure.map((e) => e.crps_lift)),
  };
}
